package com.bwzk.pojo;

public class MidTab {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.DID
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.PID
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.STBNAME
     *
     * @mbggenerated
     */
    private String stbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.TTBNAME
     *
     * @mbggenerated
     */
    private String ttbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.MTBNAME
     *
     * @mbggenerated
     */
    private String mtbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.SSQL
     *
     * @mbggenerated
     */
    private String ssql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.PIDSQL
     *
     * @mbggenerated
     */
    private String pidsql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.CALLBACKSQL
     *
     * @mbggenerated
     */
    private String callbacksql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.DEFAULTFIELD
     *
     * @mbggenerated
     */
    private String defaultfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.DEFAULTVALUE
     *
     * @mbggenerated
     */
    private String defaultvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDTB.UPDATESQL
     *
     * @mbggenerated
     */
    private String updatesql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.DID
     *
     * @return the value of P_MIDTB.DID
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.DID
     *
     * @param did the value for P_MIDTB.DID
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.PID
     *
     * @return the value of P_MIDTB.PID
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.PID
     *
     * @param pid the value for P_MIDTB.PID
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.STBNAME
     *
     * @return the value of P_MIDTB.STBNAME
     *
     * @mbggenerated
     */
    public String getStbname() {
        return stbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.STBNAME
     *
     * @param stbname the value for P_MIDTB.STBNAME
     *
     * @mbggenerated
     */
    public void setStbname(String stbname) {
        this.stbname = stbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.TTBNAME
     *
     * @return the value of P_MIDTB.TTBNAME
     *
     * @mbggenerated
     */
    public String getTtbname() {
        return ttbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.TTBNAME
     *
     * @param ttbname the value for P_MIDTB.TTBNAME
     *
     * @mbggenerated
     */
    public void setTtbname(String ttbname) {
        this.ttbname = ttbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.MTBNAME
     *
     * @return the value of P_MIDTB.MTBNAME
     *
     * @mbggenerated
     */
    public String getMtbname() {
        return mtbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.MTBNAME
     *
     * @param mtbname the value for P_MIDTB.MTBNAME
     *
     * @mbggenerated
     */
    public void setMtbname(String mtbname) {
        this.mtbname = mtbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.SSQL
     *
     * @return the value of P_MIDTB.SSQL
     *
     * @mbggenerated
     */
    public String getSsql() {
        return ssql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.SSQL
     *
     * @param ssql the value for P_MIDTB.SSQL
     *
     * @mbggenerated
     */
    public void setSsql(String ssql) {
        this.ssql = ssql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.PIDSQL
     *
     * @return the value of P_MIDTB.PIDSQL
     *
     * @mbggenerated
     */
    public String getPidsql() {
        return pidsql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.PIDSQL
     *
     * @param pidsql the value for P_MIDTB.PIDSQL
     *
     * @mbggenerated
     */
    public void setPidsql(String pidsql) {
        this.pidsql = pidsql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.CALLBACKSQL
     *
     * @return the value of P_MIDTB.CALLBACKSQL
     *
     * @mbggenerated
     */
    public String getCallbacksql() {
        return callbacksql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.CALLBACKSQL
     *
     * @param callbacksql the value for P_MIDTB.CALLBACKSQL
     *
     * @mbggenerated
     */
    public void setCallbacksql(String callbacksql) {
        this.callbacksql = callbacksql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.BZ
     *
     * @return the value of P_MIDTB.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.BZ
     *
     * @param bz the value for P_MIDTB.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.DEFAULTFIELD
     *
     * @return the value of P_MIDTB.DEFAULTFIELD
     *
     * @mbggenerated
     */
    public String getDefaultfield() {
        return defaultfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.DEFAULTFIELD
     *
     * @param defaultfield the value for P_MIDTB.DEFAULTFIELD
     *
     * @mbggenerated
     */
    public void setDefaultfield(String defaultfield) {
        this.defaultfield = defaultfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.DEFAULTVALUE
     *
     * @return the value of P_MIDTB.DEFAULTVALUE
     *
     * @mbggenerated
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.DEFAULTVALUE
     *
     * @param defaultvalue the value for P_MIDTB.DEFAULTVALUE
     *
     * @mbggenerated
     */
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDTB.UPDATESQL
     *
     * @return the value of P_MIDTB.UPDATESQL
     *
     * @mbggenerated
     */
    public String getUpdatesql() {
        return updatesql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDTB.UPDATESQL
     *
     * @param updatesql the value for P_MIDTB.UPDATESQL
     *
     * @mbggenerated
     */
    public void setUpdatesql(String updatesql) {
        this.updatesql = updatesql;
    }
}