package com.hwxt.pojo;

public class MidDbs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.DID
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.DALXCHNAME
     *
     * @mbggenerated
     */
    private String dalxchname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.LIBCODE
     *
     * @mbggenerated
     */
    private Integer libcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.DBURL
     *
     * @mbggenerated
     */
    private String dburl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.DBNAME
     *
     * @mbggenerated
     */
    private String dbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.DBTYPE
     *
     * @mbggenerated
     */
    private String dbtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.MAXLEVEL
     *
     * @mbggenerated
     */
    private String maxlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_MIDDB.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.DID
     *
     * @return the value of P_MIDDB.DID
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.DID
     *
     * @param did the value for P_MIDDB.DID
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.DALXCHNAME
     *
     * @return the value of P_MIDDB.DALXCHNAME
     *
     * @mbggenerated
     */
    public String getDalxchname() {
        return dalxchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.DALXCHNAME
     *
     * @param dalxchname the value for P_MIDDB.DALXCHNAME
     *
     * @mbggenerated
     */
    public void setDalxchname(String dalxchname) {
        this.dalxchname = dalxchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.LIBCODE
     *
     * @return the value of P_MIDDB.LIBCODE
     *
     * @mbggenerated
     */
    public Integer getLibcode() {
        return libcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.LIBCODE
     *
     * @param libcode the value for P_MIDDB.LIBCODE
     *
     * @mbggenerated
     */
    public void setLibcode(Integer libcode) {
        this.libcode = libcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.DBURL
     *
     * @return the value of P_MIDDB.DBURL
     *
     * @mbggenerated
     */
    public String getDburl() {
        return dburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.DBURL
     *
     * @param dburl the value for P_MIDDB.DBURL
     *
     * @mbggenerated
     */
    public void setDburl(String dburl) {
        this.dburl = dburl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.DBNAME
     *
     * @return the value of P_MIDDB.DBNAME
     *
     * @mbggenerated
     */
    public String getDbname() {
        return dbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.DBNAME
     *
     * @param dbname the value for P_MIDDB.DBNAME
     *
     * @mbggenerated
     */
    public void setDbname(String dbname) {
        this.dbname = dbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.DBTYPE
     *
     * @return the value of P_MIDDB.DBTYPE
     *
     * @mbggenerated
     */
    public String getDbtype() {
        return dbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.DBTYPE
     *
     * @param dbtype the value for P_MIDDB.DBTYPE
     *
     * @mbggenerated
     */
    public void setDbtype(String dbtype) {
        this.dbtype = dbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.USERNAME
     *
     * @return the value of P_MIDDB.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.USERNAME
     *
     * @param username the value for P_MIDDB.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.PASSWORD
     *
     * @return the value of P_MIDDB.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.PASSWORD
     *
     * @param password the value for P_MIDDB.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.MAXLEVEL
     *
     * @return the value of P_MIDDB.MAXLEVEL
     *
     * @mbggenerated
     */
    public String getMaxlevel() {
        return maxlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.MAXLEVEL
     *
     * @param maxlevel the value for P_MIDDB.MAXLEVEL
     *
     * @mbggenerated
     */
    public void setMaxlevel(String maxlevel) {
        this.maxlevel = maxlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_MIDDB.BZ
     *
     * @return the value of P_MIDDB.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_MIDDB.BZ
     *
     * @param bz the value for P_MIDDB.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz;
    }
}