package com.hwxt.pojo;

import java.util.ArrayList;
import java.util.List;

public class MidDbsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public MidDbsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDidIsNull() {
            addCriterion("DID is null");
            return (Criteria) this;
        }

        public Criteria andDidIsNotNull() {
            addCriterion("DID is not null");
            return (Criteria) this;
        }

        public Criteria andDidEqualTo(Integer value) {
            addCriterion("DID =", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotEqualTo(Integer value) {
            addCriterion("DID <>", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThan(Integer value) {
            addCriterion("DID >", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("DID >=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThan(Integer value) {
            addCriterion("DID <", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThanOrEqualTo(Integer value) {
            addCriterion("DID <=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidIn(List<Integer> values) {
            addCriterion("DID in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotIn(List<Integer> values) {
            addCriterion("DID not in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidBetween(Integer value1, Integer value2) {
            addCriterion("DID between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotBetween(Integer value1, Integer value2) {
            addCriterion("DID not between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDalxchnameIsNull() {
            addCriterion("DALXCHNAME is null");
            return (Criteria) this;
        }

        public Criteria andDalxchnameIsNotNull() {
            addCriterion("DALXCHNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDalxchnameEqualTo(String value) {
            addCriterion("DALXCHNAME =", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameNotEqualTo(String value) {
            addCriterion("DALXCHNAME <>", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameGreaterThan(String value) {
            addCriterion("DALXCHNAME >", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameGreaterThanOrEqualTo(String value) {
            addCriterion("DALXCHNAME >=", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameLessThan(String value) {
            addCriterion("DALXCHNAME <", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameLessThanOrEqualTo(String value) {
            addCriterion("DALXCHNAME <=", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameLike(String value) {
            addCriterion("DALXCHNAME like", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameNotLike(String value) {
            addCriterion("DALXCHNAME not like", value, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameIn(List<String> values) {
            addCriterion("DALXCHNAME in", values, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameNotIn(List<String> values) {
            addCriterion("DALXCHNAME not in", values, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameBetween(String value1, String value2) {
            addCriterion("DALXCHNAME between", value1, value2, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andDalxchnameNotBetween(String value1, String value2) {
            addCriterion("DALXCHNAME not between", value1, value2, "dalxchname");
            return (Criteria) this;
        }

        public Criteria andLibcodeIsNull() {
            addCriterion("LIBCODE is null");
            return (Criteria) this;
        }

        public Criteria andLibcodeIsNotNull() {
            addCriterion("LIBCODE is not null");
            return (Criteria) this;
        }

        public Criteria andLibcodeEqualTo(Integer value) {
            addCriterion("LIBCODE =", value, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeNotEqualTo(Integer value) {
            addCriterion("LIBCODE <>", value, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeGreaterThan(Integer value) {
            addCriterion("LIBCODE >", value, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("LIBCODE >=", value, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeLessThan(Integer value) {
            addCriterion("LIBCODE <", value, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeLessThanOrEqualTo(Integer value) {
            addCriterion("LIBCODE <=", value, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeIn(List<Integer> values) {
            addCriterion("LIBCODE in", values, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeNotIn(List<Integer> values) {
            addCriterion("LIBCODE not in", values, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeBetween(Integer value1, Integer value2) {
            addCriterion("LIBCODE between", value1, value2, "libcode");
            return (Criteria) this;
        }

        public Criteria andLibcodeNotBetween(Integer value1, Integer value2) {
            addCriterion("LIBCODE not between", value1, value2, "libcode");
            return (Criteria) this;
        }

        public Criteria andDburlIsNull() {
            addCriterion("DBURL is null");
            return (Criteria) this;
        }

        public Criteria andDburlIsNotNull() {
            addCriterion("DBURL is not null");
            return (Criteria) this;
        }

        public Criteria andDburlEqualTo(String value) {
            addCriterion("DBURL =", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlNotEqualTo(String value) {
            addCriterion("DBURL <>", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlGreaterThan(String value) {
            addCriterion("DBURL >", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlGreaterThanOrEqualTo(String value) {
            addCriterion("DBURL >=", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlLessThan(String value) {
            addCriterion("DBURL <", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlLessThanOrEqualTo(String value) {
            addCriterion("DBURL <=", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlLike(String value) {
            addCriterion("DBURL like", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlNotLike(String value) {
            addCriterion("DBURL not like", value, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlIn(List<String> values) {
            addCriterion("DBURL in", values, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlNotIn(List<String> values) {
            addCriterion("DBURL not in", values, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlBetween(String value1, String value2) {
            addCriterion("DBURL between", value1, value2, "dburl");
            return (Criteria) this;
        }

        public Criteria andDburlNotBetween(String value1, String value2) {
            addCriterion("DBURL not between", value1, value2, "dburl");
            return (Criteria) this;
        }

        public Criteria andDbnameIsNull() {
            addCriterion("DBNAME is null");
            return (Criteria) this;
        }

        public Criteria andDbnameIsNotNull() {
            addCriterion("DBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbnameEqualTo(String value) {
            addCriterion("DBNAME =", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameNotEqualTo(String value) {
            addCriterion("DBNAME <>", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameGreaterThan(String value) {
            addCriterion("DBNAME >", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameGreaterThanOrEqualTo(String value) {
            addCriterion("DBNAME >=", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameLessThan(String value) {
            addCriterion("DBNAME <", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameLessThanOrEqualTo(String value) {
            addCriterion("DBNAME <=", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameLike(String value) {
            addCriterion("DBNAME like", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameNotLike(String value) {
            addCriterion("DBNAME not like", value, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameIn(List<String> values) {
            addCriterion("DBNAME in", values, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameNotIn(List<String> values) {
            addCriterion("DBNAME not in", values, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameBetween(String value1, String value2) {
            addCriterion("DBNAME between", value1, value2, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbnameNotBetween(String value1, String value2) {
            addCriterion("DBNAME not between", value1, value2, "dbname");
            return (Criteria) this;
        }

        public Criteria andDbtypeIsNull() {
            addCriterion("DBTYPE is null");
            return (Criteria) this;
        }

        public Criteria andDbtypeIsNotNull() {
            addCriterion("DBTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDbtypeEqualTo(String value) {
            addCriterion("DBTYPE =", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeNotEqualTo(String value) {
            addCriterion("DBTYPE <>", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeGreaterThan(String value) {
            addCriterion("DBTYPE >", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeGreaterThanOrEqualTo(String value) {
            addCriterion("DBTYPE >=", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeLessThan(String value) {
            addCriterion("DBTYPE <", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeLessThanOrEqualTo(String value) {
            addCriterion("DBTYPE <=", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeLike(String value) {
            addCriterion("DBTYPE like", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeNotLike(String value) {
            addCriterion("DBTYPE not like", value, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeIn(List<String> values) {
            addCriterion("DBTYPE in", values, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeNotIn(List<String> values) {
            addCriterion("DBTYPE not in", values, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeBetween(String value1, String value2) {
            addCriterion("DBTYPE between", value1, value2, "dbtype");
            return (Criteria) this;
        }

        public Criteria andDbtypeNotBetween(String value1, String value2) {
            addCriterion("DBTYPE not between", value1, value2, "dbtype");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andMaxlevelIsNull() {
            addCriterion("MAXLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMaxlevelIsNotNull() {
            addCriterion("MAXLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMaxlevelEqualTo(String value) {
            addCriterion("MAXLEVEL =", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelNotEqualTo(String value) {
            addCriterion("MAXLEVEL <>", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelGreaterThan(String value) {
            addCriterion("MAXLEVEL >", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelGreaterThanOrEqualTo(String value) {
            addCriterion("MAXLEVEL >=", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelLessThan(String value) {
            addCriterion("MAXLEVEL <", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelLessThanOrEqualTo(String value) {
            addCriterion("MAXLEVEL <=", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelLike(String value) {
            addCriterion("MAXLEVEL like", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelNotLike(String value) {
            addCriterion("MAXLEVEL not like", value, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelIn(List<String> values) {
            addCriterion("MAXLEVEL in", values, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelNotIn(List<String> values) {
            addCriterion("MAXLEVEL not in", values, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelBetween(String value1, String value2) {
            addCriterion("MAXLEVEL between", value1, value2, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andMaxlevelNotBetween(String value1, String value2) {
            addCriterion("MAXLEVEL not between", value1, value2, "maxlevel");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_MIDDB
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_MIDDB
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}