package com.hwxt.pojo;

public class MidFieldMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.DID
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.PPID
     *
     * @mbggenerated
     */
    private Integer ppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.PID
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.SFIELD
     *
     * @mbggenerated
     */
    private String sfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.TFIELD
     *
     * @mbggenerated
     */
    private String tfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.DEFAULTVALUE
     *
     * @mbggenerated
     */
    private String defaultvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_Z430.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.DID
     *
     * @return the value of P_Z430.DID
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.DID
     *
     * @param did the value for P_Z430.DID
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.PPID
     *
     * @return the value of P_Z430.PPID
     *
     * @mbggenerated
     */
    public Integer getPpid() {
        return ppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.PPID
     *
     * @param ppid the value for P_Z430.PPID
     *
     * @mbggenerated
     */
    public void setPpid(Integer ppid) {
        this.ppid = ppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.PID
     *
     * @return the value of P_Z430.PID
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.PID
     *
     * @param pid the value for P_Z430.PID
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.SFIELD
     *
     * @return the value of P_Z430.SFIELD
     *
     * @mbggenerated
     */
    public String getSfield() {
        return sfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.SFIELD
     *
     * @param sfield the value for P_Z430.SFIELD
     *
     * @mbggenerated
     */
    public void setSfield(String sfield) {
        this.sfield = sfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.TFIELD
     *
     * @return the value of P_Z430.TFIELD
     *
     * @mbggenerated
     */
    public String getTfield() {
        return tfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.TFIELD
     *
     * @param tfield the value for P_Z430.TFIELD
     *
     * @mbggenerated
     */
    public void setTfield(String tfield) {
        this.tfield = tfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.DEFAULTVALUE
     *
     * @return the value of P_Z430.DEFAULTVALUE
     *
     * @mbggenerated
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.DEFAULTVALUE
     *
     * @param defaultvalue the value for P_Z430.DEFAULTVALUE
     *
     * @mbggenerated
     */
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_Z430.BZ
     *
     * @return the value of P_Z430.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_Z430.BZ
     *
     * @param bz the value for P_Z430.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz;
    }
}