package com.hwxt.pojo;

import java.util.ArrayList;
import java.util.List;

public class MidTabExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public MidTabExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDidIsNull() {
            addCriterion("DID is null");
            return (Criteria) this;
        }

        public Criteria andDidIsNotNull() {
            addCriterion("DID is not null");
            return (Criteria) this;
        }

        public Criteria andDidEqualTo(Integer value) {
            addCriterion("DID =", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotEqualTo(Integer value) {
            addCriterion("DID <>", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThan(Integer value) {
            addCriterion("DID >", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("DID >=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThan(Integer value) {
            addCriterion("DID <", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThanOrEqualTo(Integer value) {
            addCriterion("DID <=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidIn(List<Integer> values) {
            addCriterion("DID in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotIn(List<Integer> values) {
            addCriterion("DID not in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidBetween(Integer value1, Integer value2) {
            addCriterion("DID between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotBetween(Integer value1, Integer value2) {
            addCriterion("DID not between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("PID is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("PID is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("PID =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("PID <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("PID >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("PID >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("PID <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("PID <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("PID in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("PID not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("PID between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("PID not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andStbnameIsNull() {
            addCriterion("STBNAME is null");
            return (Criteria) this;
        }

        public Criteria andStbnameIsNotNull() {
            addCriterion("STBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andStbnameEqualTo(String value) {
            addCriterion("STBNAME =", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameNotEqualTo(String value) {
            addCriterion("STBNAME <>", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameGreaterThan(String value) {
            addCriterion("STBNAME >", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameGreaterThanOrEqualTo(String value) {
            addCriterion("STBNAME >=", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameLessThan(String value) {
            addCriterion("STBNAME <", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameLessThanOrEqualTo(String value) {
            addCriterion("STBNAME <=", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameLike(String value) {
            addCriterion("STBNAME like", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameNotLike(String value) {
            addCriterion("STBNAME not like", value, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameIn(List<String> values) {
            addCriterion("STBNAME in", values, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameNotIn(List<String> values) {
            addCriterion("STBNAME not in", values, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameBetween(String value1, String value2) {
            addCriterion("STBNAME between", value1, value2, "stbname");
            return (Criteria) this;
        }

        public Criteria andStbnameNotBetween(String value1, String value2) {
            addCriterion("STBNAME not between", value1, value2, "stbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameIsNull() {
            addCriterion("TTBNAME is null");
            return (Criteria) this;
        }

        public Criteria andTtbnameIsNotNull() {
            addCriterion("TTBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andTtbnameEqualTo(String value) {
            addCriterion("TTBNAME =", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameNotEqualTo(String value) {
            addCriterion("TTBNAME <>", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameGreaterThan(String value) {
            addCriterion("TTBNAME >", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameGreaterThanOrEqualTo(String value) {
            addCriterion("TTBNAME >=", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameLessThan(String value) {
            addCriterion("TTBNAME <", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameLessThanOrEqualTo(String value) {
            addCriterion("TTBNAME <=", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameLike(String value) {
            addCriterion("TTBNAME like", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameNotLike(String value) {
            addCriterion("TTBNAME not like", value, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameIn(List<String> values) {
            addCriterion("TTBNAME in", values, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameNotIn(List<String> values) {
            addCriterion("TTBNAME not in", values, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameBetween(String value1, String value2) {
            addCriterion("TTBNAME between", value1, value2, "ttbname");
            return (Criteria) this;
        }

        public Criteria andTtbnameNotBetween(String value1, String value2) {
            addCriterion("TTBNAME not between", value1, value2, "ttbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameIsNull() {
            addCriterion("MTBNAME is null");
            return (Criteria) this;
        }

        public Criteria andMtbnameIsNotNull() {
            addCriterion("MTBNAME is not null");
            return (Criteria) this;
        }

        public Criteria andMtbnameEqualTo(String value) {
            addCriterion("MTBNAME =", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameNotEqualTo(String value) {
            addCriterion("MTBNAME <>", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameGreaterThan(String value) {
            addCriterion("MTBNAME >", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameGreaterThanOrEqualTo(String value) {
            addCriterion("MTBNAME >=", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameLessThan(String value) {
            addCriterion("MTBNAME <", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameLessThanOrEqualTo(String value) {
            addCriterion("MTBNAME <=", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameLike(String value) {
            addCriterion("MTBNAME like", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameNotLike(String value) {
            addCriterion("MTBNAME not like", value, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameIn(List<String> values) {
            addCriterion("MTBNAME in", values, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameNotIn(List<String> values) {
            addCriterion("MTBNAME not in", values, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameBetween(String value1, String value2) {
            addCriterion("MTBNAME between", value1, value2, "mtbname");
            return (Criteria) this;
        }

        public Criteria andMtbnameNotBetween(String value1, String value2) {
            addCriterion("MTBNAME not between", value1, value2, "mtbname");
            return (Criteria) this;
        }

        public Criteria andSsqlIsNull() {
            addCriterion("SSQL is null");
            return (Criteria) this;
        }

        public Criteria andSsqlIsNotNull() {
            addCriterion("SSQL is not null");
            return (Criteria) this;
        }

        public Criteria andSsqlEqualTo(String value) {
            addCriterion("SSQL =", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlNotEqualTo(String value) {
            addCriterion("SSQL <>", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlGreaterThan(String value) {
            addCriterion("SSQL >", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlGreaterThanOrEqualTo(String value) {
            addCriterion("SSQL >=", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlLessThan(String value) {
            addCriterion("SSQL <", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlLessThanOrEqualTo(String value) {
            addCriterion("SSQL <=", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlLike(String value) {
            addCriterion("SSQL like", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlNotLike(String value) {
            addCriterion("SSQL not like", value, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlIn(List<String> values) {
            addCriterion("SSQL in", values, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlNotIn(List<String> values) {
            addCriterion("SSQL not in", values, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlBetween(String value1, String value2) {
            addCriterion("SSQL between", value1, value2, "ssql");
            return (Criteria) this;
        }

        public Criteria andSsqlNotBetween(String value1, String value2) {
            addCriterion("SSQL not between", value1, value2, "ssql");
            return (Criteria) this;
        }

        public Criteria andPidsqlIsNull() {
            addCriterion("PIDSQL is null");
            return (Criteria) this;
        }

        public Criteria andPidsqlIsNotNull() {
            addCriterion("PIDSQL is not null");
            return (Criteria) this;
        }

        public Criteria andPidsqlEqualTo(String value) {
            addCriterion("PIDSQL =", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlNotEqualTo(String value) {
            addCriterion("PIDSQL <>", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlGreaterThan(String value) {
            addCriterion("PIDSQL >", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlGreaterThanOrEqualTo(String value) {
            addCriterion("PIDSQL >=", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlLessThan(String value) {
            addCriterion("PIDSQL <", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlLessThanOrEqualTo(String value) {
            addCriterion("PIDSQL <=", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlLike(String value) {
            addCriterion("PIDSQL like", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlNotLike(String value) {
            addCriterion("PIDSQL not like", value, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlIn(List<String> values) {
            addCriterion("PIDSQL in", values, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlNotIn(List<String> values) {
            addCriterion("PIDSQL not in", values, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlBetween(String value1, String value2) {
            addCriterion("PIDSQL between", value1, value2, "pidsql");
            return (Criteria) this;
        }

        public Criteria andPidsqlNotBetween(String value1, String value2) {
            addCriterion("PIDSQL not between", value1, value2, "pidsql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlIsNull() {
            addCriterion("CALLBACKSQL is null");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlIsNotNull() {
            addCriterion("CALLBACKSQL is not null");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlEqualTo(String value) {
            addCriterion("CALLBACKSQL =", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlNotEqualTo(String value) {
            addCriterion("CALLBACKSQL <>", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlGreaterThan(String value) {
            addCriterion("CALLBACKSQL >", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlGreaterThanOrEqualTo(String value) {
            addCriterion("CALLBACKSQL >=", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlLessThan(String value) {
            addCriterion("CALLBACKSQL <", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlLessThanOrEqualTo(String value) {
            addCriterion("CALLBACKSQL <=", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlLike(String value) {
            addCriterion("CALLBACKSQL like", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlNotLike(String value) {
            addCriterion("CALLBACKSQL not like", value, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlIn(List<String> values) {
            addCriterion("CALLBACKSQL in", values, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlNotIn(List<String> values) {
            addCriterion("CALLBACKSQL not in", values, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlBetween(String value1, String value2) {
            addCriterion("CALLBACKSQL between", value1, value2, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andCallbacksqlNotBetween(String value1, String value2) {
            addCriterion("CALLBACKSQL not between", value1, value2, "callbacksql");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldIsNull() {
            addCriterion("DEFAULTFIELD is null");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldIsNotNull() {
            addCriterion("DEFAULTFIELD is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldEqualTo(String value) {
            addCriterion("DEFAULTFIELD =", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldNotEqualTo(String value) {
            addCriterion("DEFAULTFIELD <>", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldGreaterThan(String value) {
            addCriterion("DEFAULTFIELD >", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULTFIELD >=", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldLessThan(String value) {
            addCriterion("DEFAULTFIELD <", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldLessThanOrEqualTo(String value) {
            addCriterion("DEFAULTFIELD <=", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldLike(String value) {
            addCriterion("DEFAULTFIELD like", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldNotLike(String value) {
            addCriterion("DEFAULTFIELD not like", value, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldIn(List<String> values) {
            addCriterion("DEFAULTFIELD in", values, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldNotIn(List<String> values) {
            addCriterion("DEFAULTFIELD not in", values, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldBetween(String value1, String value2) {
            addCriterion("DEFAULTFIELD between", value1, value2, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultfieldNotBetween(String value1, String value2) {
            addCriterion("DEFAULTFIELD not between", value1, value2, "defaultfield");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIsNull() {
            addCriterion("DEFAULTVALUE is null");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIsNotNull() {
            addCriterion("DEFAULTVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueEqualTo(String value) {
            addCriterion("DEFAULTVALUE =", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotEqualTo(String value) {
            addCriterion("DEFAULTVALUE <>", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueGreaterThan(String value) {
            addCriterion("DEFAULTVALUE >", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULTVALUE >=", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLessThan(String value) {
            addCriterion("DEFAULTVALUE <", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLessThanOrEqualTo(String value) {
            addCriterion("DEFAULTVALUE <=", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLike(String value) {
            addCriterion("DEFAULTVALUE like", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotLike(String value) {
            addCriterion("DEFAULTVALUE not like", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIn(List<String> values) {
            addCriterion("DEFAULTVALUE in", values, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotIn(List<String> values) {
            addCriterion("DEFAULTVALUE not in", values, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueBetween(String value1, String value2) {
            addCriterion("DEFAULTVALUE between", value1, value2, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotBetween(String value1, String value2) {
            addCriterion("DEFAULTVALUE not between", value1, value2, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlIsNull() {
            addCriterion("UPDATESQL is null");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlIsNotNull() {
            addCriterion("UPDATESQL is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlEqualTo(String value) {
            addCriterion("UPDATESQL =", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlNotEqualTo(String value) {
            addCriterion("UPDATESQL <>", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlGreaterThan(String value) {
            addCriterion("UPDATESQL >", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATESQL >=", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlLessThan(String value) {
            addCriterion("UPDATESQL <", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlLessThanOrEqualTo(String value) {
            addCriterion("UPDATESQL <=", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlLike(String value) {
            addCriterion("UPDATESQL like", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlNotLike(String value) {
            addCriterion("UPDATESQL not like", value, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlIn(List<String> values) {
            addCriterion("UPDATESQL in", values, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlNotIn(List<String> values) {
            addCriterion("UPDATESQL not in", values, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlBetween(String value1, String value2) {
            addCriterion("UPDATESQL between", value1, value2, "updatesql");
            return (Criteria) this;
        }

        public Criteria andUpdatesqlNotBetween(String value1, String value2) {
            addCriterion("UPDATESQL not between", value1, value2, "updatesql");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_MIDTB
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}