package com.bwzk.dao.i;

import com.bwzk.dao.BaseDao;
import com.bwzk.pojo.MidFieldMapping;
import com.bwzk.pojo.MidFieldMappingExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MidFieldMappingMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int countByExample(MidFieldMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int deleteByExample(MidFieldMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int insert(MidFieldMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int insertSelective(MidFieldMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    List<MidFieldMapping> selectByExample(MidFieldMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    MidFieldMapping selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MidFieldMapping record, @Param("example") MidFieldMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MidFieldMapping record, @Param("example") MidFieldMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MidFieldMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_Z430
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MidFieldMapping record);
}