package com.bwzk.dao.i;

import com.bwzk.dao.BaseDao;
import com.bwzk.pojo.MidTab;
import com.bwzk.pojo.MidTabExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MidTabMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int countByExample(MidTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int deleteByExample(MidTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int insert(MidTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int insertSelective(MidTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    List<MidTab> selectByExample(MidTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    MidTab selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MidTab record, @Param("example") MidTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MidTab record, @Param("example") MidTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MidTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table P_MIDTB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MidTab record);
}